# Generated by Django 5.0.6 on 2024-11-20 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deposit_balance',
            field=models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Deposit_Balance'),
        ),
    ]
